const express = require('express');
const connectDB = require('./config/db');
const cors = require('cors');
require('dotenv').config();
const app = express();
connectDB();
app.use(express.json({ extended: false }));
app.use(cors());
app.use('/api/users', require('./routes/user'));
app.use('/api/complaints', require('./routes/complaint'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server started on port ${PORT}`));
